### ISSUE TITLE
e2e tests exercise the installer

### ISSUE THREAD

**Issue by jamiemonserrate** [vmware-tanzu/cluster-api-provider-bringyourownhost#231]
**Describe the solution you'd like**
At the moment, we skip running the installer in our e2e tests. This is because the containers need to run in privileged mode, and they end up making kernel changes on the system they are running on. 

We should have the tests spin up a VM, and then run the BYOH host containers in this VM, so that the users system is untouched. Once we do that, we should enable the installer to run in our e2e tests.

**Comment by anusha94** [comment]
Running e2e test with docker containers as byohosts in CI - https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/pull/313

When it comes to local, since we modify some host config, the plan is to notify the user of the kernel config changes we will be making and ask for a process yes / no option.
@jamiemonserrate & I contemplated on spinning up a new VM and running the test in this VM, but this workflow is not so easily achievable in CI. Because, nested virtualization is not supported atm in GH runners that we use - see https://github.com/actions/virtual-environments/issues/183
We do not want separate workflows for dev and CI, hence giving a warning to the user when running e2e locally. It is upto the user to continue running the test or spin up their own VMs and run the tests there.
