### ISSUE TITLE
Make target "prepare-byoh-docker-host-image" throwing error in Ubuntu 18.04

### ISSUE THREAD

**Issue by dharmjit** [vmware-tanzu/cluster-api-provider-bringyourownhost#296]
**What steps did you take and what happened:**
While trying [Getting Started Guide](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/docs/getting_started.md) with docker hosts, the below make target is failing on Ubuntu 18.04 host machine.
```
> make prepare-byoh-docker-host-image
E: Unable to locate package linux-image-4.15.0-161-generic
E: Couldn't find any package by glob 'linux-image-4.15.0-161-generic'
E: Couldn't find any package by regex 'linux-image-4.15.0-161-generic'
```

**What did you expect to happen:**
The host image should be created successfully, which could be further used to run the agent on and create workload cluster.

**Anything else you would like to add:**
It seems like a kernel mismatch for byoh docker image(Ubuntu 20.04) and the host(ubuntu 18.04) as the same is not faced while creating the image on Ubuntu 20.04.

**Environment:**

- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 Host

**Comment by NilanjanDaw** [comment]
I guess the `linux-image-*` binary requirements are because of the `kernel config` files required as part of the preflight checks during `kubeadm` cluster initialization. 

 In such a case can we just copy the `kernel config` file from the host to a virtual path within the docker image and remove the `linux-image` dependency?

**Comment by anusha94** [comment]
>In such a case can we just copy the kernel config file from the host to a virtual path within the docker image and remove the linux-image dependency?

Based on your host, the kernel config file path may be different. How about keeping it as it is and add a disclaimer on what hosts / OSes the getting-started guide will seamlessly work and what changes you might need otherwise?

Because it will become difficult to cater to a variety of OS flavors. Thoughts?

**Comment by NilanjanDaw** [comment]
Adding a disclaimer in the docs sounds good. I am guessing the header mismatch will occur if the docker base and the host OS's kernels do not match (at least the major version). We can validate this and add a disclaimer to that effect in the documentation.

**Comment by NilanjanDaw** [comment]
I can take a look into this.
