### ISSUE TITLE
Unit tests for certificate rotation

### ISSUE THREAD

**Issue by sachinkumarsingh092** [vmware-tanzu/cluster-api-provider-bringyourownhost#656]
After #555, we need to write e2e tests for the same as the minimum time for certificate expiration is 10 minutes so this will be a slow test.

**Comment by shivi28** [comment]
Renaming it to unit test because as per our findings, the integration test for this feature is seemingly complex because creating a local kubeconfig that has < 1min expiry involves copying a lot of code from controller-runtime's internal testing package. So keeping the scope of this issue limited to unit test only.
